language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
matrix:
  include:
    - node_js: 16
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  allow_failures:
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
cache: yarn
before_script:
  - yarn run build
script:
  - yarn run coverage
after_script:
  - npx coveralls < ./coverage/lcov.info
